name: Deploy website
on: [push, workflow_dispatch]
# on: 
  # pull_request:
    # types:[opened, closed]
    # types:
    # - opened
    # - closed
  # push:
    # branches:
      # - main # main
      # - 'dev-*' # dev-new dev-this-is-new
      # - 'feat/**' # feat/new feat/new/button
    # paths-ignore:
      # - '.github/workflows/*'
  # workflow_dispatch:
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello World!!!"
      - name: Print goodbye
        run: echo "Done - bye!!!"
      - name: Multi-Line Shell commands
        run: |
           echo "First output"
           echo "Second output"
  test:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install dependencies
        run: npm ci
      - name: Lint code
        run: npm run
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.something }}
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Publish JS filename
        id: publish
        run: find dist/assets/*.js -type f -execdir echo 'something={}' >> $GITHUB_OUTPUT ';'
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dist
          # path: |
          #   dist
          #   package.json
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4              
        with:
          name: dist-files
      - name: Output contents
        run: ls
      - name: Output filename
        run: echo "${{ needs.build }}"
      - name: Deploy
        run: echo "Deploying..."
      
  
