name: Output information
on: workflow_dispatch
jobs:
  info-job:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context
        run: echo "${{ toJSON(github) }}"
  issues-job:
    runs-on: ubuntu-latest
    steps:
      - name: Output issues event
        run: echo "${{ toJSON(issues) }}
